// Общее
export const SUBSYSTEMS_FETCH_REQUESTED = 'REPORT_SUBSYSTEMS_FETCH_REQUESTED';
export const SET_SUBSYSTEMS = 'REPORT_SET_SUBSYSTEMS';
export const SET_SUBSYSTEMS_LOADING_STATE = 'REPORT_SET_SUBSYSTEMS_LOADING_STATE';

// Реестр отчётов
export const REPORTS_LIST_FETCH_REQUESTED = 'REPORT_REPORT_LIST_FETCH_REQUESTED';
export const SET_REPORTS_LIST = 'REPORT_SET_REPORTS_LIST';
export const SET_REPORTS_LIST_LOADING_STATE = 'REPORT_SET_REPORTS_LIST_LOADING_STATE'

export const STORE_REPORT_REQUESTED = 'REPORT_STORE_REPORT_REQUESTED';

export const REMOVE_REPORT_REQUESTED = 'REPORT_REMOVE_REPORT_REQUESTED';
export const REMOVE_REPORT = 'REPORT_REMOVE_REPORT';

// Редактор отчётов
export const INITIALIZE_EDITOR = 'REPORT_INITIALIZE_EDITOR';
export const CLEAR_EDITOR = 'REPORT_CLEAR_EDITOR';
export const ADD_FIELDS_REQUESTED = 'REPORT_ADD_FIELDS_REQUESTED';
export const APPLY_NEW_STATE = 'REPORT_APPLY_NEW_STATE';
export const REMOVE_FIELD_REQUESTED = 'REPORT_REMOVE_FIELD_REQUESTED';
export const CHANGE_FIELD_REQUESTED = 'REPORT_CHANGE_FIELD_REQUESTED';
export const REORDER_FIELDS_REQUESTED = 'REPORT_REORDER_FIELDS_REQUESTED';

export const ADD_SETTING_REQUESTED = 'REPORT_ADD_SETTING_REQUESTED';
export const CHANGE_SETTINGS_TAB = 'REPORT_CHANGE_SETTINGS_TAB';
export const CHANGE_FILTER_REQUESTED = 'REPORT_CHANGE_FILTER_REQUESTED';
export const REMOVE_FILTER_REQUESTED = 'REPORT_REMOVE_FILTER_REQUESTED';
export const CHANGE_SORT_REQUESTED = 'REPORT_CHANGE_SORT_REQUESTED';
export const REMOVE_SORT_REQUESTED = 'REPORT_REMOVE_SORT_REQUESTED';
export const REORDER_SORT_REQUESTED = 'REPORT_REORDER_SORT_REQUESTED';
export const REMOVE_GROUP_REQUESTED = 'REPORT_REMOVE_GROUP_REQUESTED';
export const REORDER_GROUP_REQUESTED = 'REPORT_REORDER_GROUP_REQUESTED';
export const CHANGE_TOTAL_REQUESTED = 'REPORT_CHANGE_TOTAL_REQUESTED';
export const REMOVE_TOTAL_REQUESTED = 'REPORT_REMOVE_TOTAL_REQUESTED';

export const SET_CHART_DATA = 'REPORT_SET_CHART_DATA';
export const APPLY_CHART_NAME = 'REPORT_APPLY_CHART_NAME';
export const SET_DATA_AXIS_KEY_REQUESTED = 'REPORT_SET_DATA_AXIS_KEY_REQUESTED';
export const ADD_VALUE_AXIS_REQUESTED = 'REPORT_ADD_VALUE_AXIS_REQUESTED';
export const REMOVE_VALUE_AXIS_REQUESTED = 'REPORT_REMOVE_VALUE_AXIS_REQUESTED';
export const CHANGE_VALUE_AXIS_REQUESTED = 'REPORT_CHANGE_VALUE_AXIS_REQUESTED';


export const LOAD_REQUESTED = 'REPORT_LOAD_REQUESTED';
export const LOAD = 'REPORT_LOAD';
export const SAVE_REQUESTED = 'REPORT_SAVE_REQUESTED';
