// Общее
export const SUBSYSTEMS_FETCH_REQUESTED = 'RBU_SUBSYSTEMS_FETCH_REQUESTED';
export const SET_SUBSYSTEMS = 'RBU_SET_SUBSYSTEMS';
export const SET_SUBSYSTEMS_LOADING_STATE = 'RBU_SET_SUBSYSTEMS_LOADING_STATE';

// Реестр отчётов
export const REPORTS_LIST_FETCH_REQUESTED = 'RBU_REPORTS_LIST_FETCH_REQUESTED';
export const SET_REPORTS_LIST = 'RBU_SET_REPORTS_LIST';
export const SET_REPORTS_LIST_LOADING_STATE = 'RBU_SET_REPORTS_LIST_LOADING_STATE'

export const STORE_REPORT_REQUESTED = 'RBU_STORE_REPORT_REQUESTED';

export const REMOVE_REPORT_REQUESTED = 'RBU_REMOVE_REPORT_REQUESTED';
export const REMOVE_REPORT = 'RBU_REMOVE_REPORT';

// Редактор отчётов
export const INITIALIZE_EDITOR = 'RBU_INITIALIZE_EDITOR';
export const CLEAR_EDITOR = 'RBU_CLEAR_EDITOR';
export const ADD_FIELDS_REQUESTED = 'RBU_ADD_FIELDS_REQUESTED';
export const APPLY_NEW_STATE = 'RBU_APPLY_NEW_STATE';
export const REMOVE_FIELD_REQUESTED = 'RBU_REMOVE_FIELD_REQUESTED';
export const CHANGE_FIELD_REQUESTED = 'RBU_CHANGE_FIELD_REQUESTED';
export const REORDER_FIELDS_REQUESTED = 'RBU_REORDER_FIELDS_REQUESTED';

export const ADD_SETTING_REQUESTED = 'RBU_ADD_SETTING_REQUESTED';
export const CHANGE_SETTINGS_TAB = 'RBU_CHANGE_SETTINGS_TAB';
export const CHANGE_FILTER_REQUESTED = 'RBU_CHANGE_FILTER_REQUESTED';
export const REMOVE_FILTER_REQUESTED = 'RBU_REMOVE_FILTER_REQUESTED';
export const CHANGE_SORT_REQUESTED = 'RBU_CHANGE_SORT_REQUESTED';
export const REMOVE_SORT_REQUESTED = 'RBU_REMOVE_SORT_REQUESTED';
export const REORDER_SORT_REQUESTED = 'RBU_REORDER_SORT_REQUESTED';
export const REMOVE_GROUP_REQUESTED = 'RBU_REMOVE_GROUP_REQUESTED';
export const REORDER_GROUP_REQUESTED = 'RBU_REORDER_GROUP_REQUESTED';
export const CHANGE_TOTAL_REQUESTED = 'RBU_CHANGE_TOTAL_REQUESTED';
export const REMOVE_TOTAL_REQUESTED = 'RBU_REMOVE_TOTAL_REQUESTED';

export const SET_REPORT_TYPE = 'RBU_SET_REPORT_TYPE';
export const SET_CHART_DATA = 'RBU_SET_CHART_DATA';
export const APPLY_CHART_NAME = 'RBU_APPLY_CHART_NAME';
export const SET_DATA_AXIS_KEY_REQUESTED = 'RBU_SET_DATA_AXIS_KEY_REQUESTED';
export const ADD_VALUE_AXIS_REQUESTED = 'RBU_ADD_VALUE_AXIS_REQUESTED';
export const REMOVE_VALUE_AXIS_REQUESTED = 'RBU_REMOVE_VALUE_AXIS_REQUESTED';
export const CHANGE_VALUE_AXIS_REQUESTED = 'RBU_CHANGE_VALUE_AXIS_REQUESTED';


export const LOAD_REQUESTED = 'RBU_LOAD_REQUESTED';
export const LOAD = 'RBU_LOAD';
export const SAVE_REQUESTED = 'RBU_SAVE_REQUESTED';
